### ISSUE TITLE
Map not showing up in android

### ISSUE THREAD

**Issue by Nate-Wessel** [gaslight/bus-detective#17]
Using the android app, the map at the top of the arrival predictions pages fails to show up. The space for it is still there but none of the tiles seem to load. This doesn't happen with the web app. Tried on two different android devices.

**Comment by ktornwall** [comment]
Thanks for reporting this! I think I know the issue. :)

**Comment by ktornwall** [comment]
Hi @Nate-Wessel,

I tried to reproduce this on the simulator and was not able to see the issue. Now, we have changed to open maps since then so that could be the difference. The only other thing I can think of is that maybe you ran into the old favorites issue? I wrote it up on Trello: https://trello.com/c/dCY58IZX

If you could check and see if this is still an issue for you, I would really appreciate it. :)

Thanks,
KT

**Comment by Nate-Wessel** [comment]
KT,
It looks like it's working now. I'm pretty sure it was trying to use Google maps when I had the problem. 

-Nate
